version: "3.8"

services:
  nginx:
    build: 
      context: ./nginx
    container_name: "nginx_cont"
    ports:
      - "81:81"
    restart: always 
    depends_on:
      - django
    networks:
      - notes-app


  django:
    build:
      context: .
    container_name: "django_cont"
    env_file:
      - .env
    restart: always
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    networks:
      - notes-app
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  


  db:
    container_name: "db_cont"
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
    volumes:
      - ~/.docker-volumes/notes-app/mysql/data:/var/lib/mysql
    networks:
      - notes-app
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost","-uroot","-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


volumes:
  mysql-data:
    driver: local

networks:
  notes-app:
    driver: bridge
